SELECT * FROM movie.movie_data;

# Top Movies by Revenue
SELECT name, gross
FROM movie.movie_data
ORDER BY gross DESC
LIMIT 10;


# Number of Movies Released Per Year
SELECT year, count(name)
FROM movie.movie_data
group by year;


# Average Rating by Genre
SELECT genre as Genre, round(AVG(score),2) AS "Average Rating"
FROM movie.movie_data
GROUP BY genre;


# Most Common Movie Genre
SELECT genre, COUNT(*) AS genre_count
FROM movie.movie_data
GROUP BY genre
ORDER BY genre_count DESC
LIMIT 1;


# Top 5 Directors with the most works
SELECT  director AS Director, COUNT(name) AS Total_Movies
FROM movie.movie_data
GROUP BY  director
ORDER BY Total_Movies DESC
LIMIT 5;


# Highest-Grossing Movies by Genre
SELECT genre AS Genre, name AS Title, gross AS "Highest Gross"
FROM   movie.movie_data AS m1
WHERE gross = (
        SELECT MAX(gross) 
        FROM movie.movie_data AS m2
        WHERE m1.genre = m2.genre
    );


# Average Movie Duration by Year
SELECT year as "Year", Round(AVG(runtime),2) AS "Average Duration (in mins)"
FROM movie.movie_data
GROUP BY year
ORDER BY year;


# Revenue Trend Over Time (total revenue generated by movies each year)
SELECT year as Year, SUM(gross) AS "Total Revenue"
FROM movie.movie_data
GROUP BY year
ORDER BY year;


# Top Actors Appearing in the Most Movies
SELECT star, COUNT(*) AS movie_count
FROM movie.movie_data
GROUP BY star
ORDER BY movie_count DESC
LIMIT 10;


# Lowest-Rated Movies by Year
SELECT year, name, score AS min_rating
FROM   movie.movie_data AS m1
WHERE score = (
        SELECT MiN(score) 
        FROM movie.movie_data AS m2
        WHERE m1.genre = m2.genre
    );


# Top 10 Most Profitable Movies
SELECT name, (gross - budget) AS profit
FROM movie.movie_data
ORDER BY profit DESC
LIMIT 10;


# Directors with the Longest Average Movie Duration
SELECT director AS "Director", ROUND(AVG(runtime), 2) AS "Average Duration (mins)"
FROM movie.movie_data
GROUP BY director
ORDER BY "Average Duration (mins)" DESC
LIMIT 10;


# Most Common Movie Rating
SELECT rating AS "Rating", COUNT(*) AS "Number of Movies"
FROM movie.movie_data
GROUP BY rating
ORDER BY "Number of Movies" DESC
LIMIT 1;


# Directors with the Most Movies in a Specific Genre
SELECT director AS "Director", COUNT(*) AS "Number of Movies"
FROM movie.movie_data
WHERE genre = 'Action'
GROUP BY director
ORDER BY "Number of Movies" DESC
LIMIT 5;


# Most Common Movie Rating
SELECT rating AS "Rating", 
       COUNT(*) AS "Number of Movies"
FROM movie.movie_data
GROUP BY rating
ORDER BY COUNT(*) DESC;

